import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Button } from "primereact/button";

import React, { useState } from 'react';
import { InputText } from 'primereact/inputtext';

    
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [value1, setValue1] = useState('');
const [value2, setValue2] = useState('');
const [value3, setValue3] = useState('');
const [value4, setValue4] = useState('');
const [value5, setValue5] = useState('');
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <div>
            <div className="card">
                <h5>Basic</h5>
                <InputText value={value1} onChange={(e) => setValue1(e.target.value)} />
                <span className="ml-2">{value1}</span>

                <h5>Floating Label</h5>
                <span className="p-float-label">
                    <InputText id="username" value={value2} onChange={(e) => setValue2(e.target.value)} />
                    <label htmlFor="username">Username</label>
                </span>

                <h5>Left Icon</h5>
                <span className="p-input-icon-left">
                    <i className="pi pi-search" />
                    <InputText value={value3} onChange={(e) => setValue3(e.target.value)} placeholder="Search" />
                </span>

                <h5>Right Icon</h5>
                <span className="p-input-icon-right">
                    <i className="pi pi-spin pi-spinner" />
                    <InputText value={value4} onChange={(e) => setValue4(e.target.value)} />
                </span>

                <h5>Help Text</h5>
                <div className="field">
                    <label htmlFor="username1" className="block">Username</label>
                    <InputText id="username1" aria-describedby="username1-help" className="block"/>
                    <small id="username1-help" className="block">Enter your username to reset your password.</small>
                </div>

                <h5>Invalid</h5>
                <div className="field">
                    <label htmlFor="username2" className="block">Username</label>
                    <InputText id="username2" aria-describedby="username2-help" className="p-invalid block" />
                    <small id="username2-help" className="p-error block">Username is not available.</small>
                </div>

                <h5>Disabled</h5>
                <InputText value={value5} disabled />

                <h5>Sizes</h5>
                <div className="sizes">
                    <InputText type="text" className="p-inputtext-sm block mb-2" placeholder="Small" />
                    <InputText type="text" className="block mb-2" placeholder="Normal" />
                    <InputText type="text" className="p-inputtext-lg block"  placeholder="Large" />
                </div>
            </div>
        </div>
    </>
  )
}
